use mydb;
INSERT INTO Resultat_academic (Nom_resultat_acad)
VALUES ('Promociona'),
    ('Repeteix'),
    ('Abandona estudis'),
    ('No opta plaça'),
    ('Accés al món laboral');
INSERT INTO Motiu_baixa (Nom_motiu_baixa)
VALUES ('Quotes impagades'),
    ('Fan altres activitats'),
    ('Comportament disruptiu'),
    ('La família no vol que segueixi veí'),
    ('Falta assistència recurrent'),
    ('L''infant no vol tornar'),
    ('Canvi de centre'),
    ('Trasllat familiar a una altra ciutat'),
    ('Desemparament'),
    ('Altres');
INSERT INTO Risc (Nivel)
VALUES ('Sense risc'),
    ('Lleu'),
    ('Moderat'),
    ('Alt');
INSERT INTO Pais (Nom_pais)
VALUES ('Albania'),
    ('Alemanya'),
    ('Algeria'),
    ('Andorra'),
    ('Angola'),
    ('Anguilla'),
    ('Antartida'),
    ('Antigua i Barbuda'),
    ('Arabia Saudita'),
    ('Armenia'),
    ('Aruba'),
    ('Australia'),
    ('Austria'),
    ('Azerbaidjan'),
    ('Bahames'),
    ('Bahrain'),
    ('Bangladesh'),
    ('Barbados'),
    ('Belarus'),
    ('Belgica'),
    ('Belize'),
    ('Benim'),
    ('Bermudes'),
    ('Bhutan'),
    ('Bolivia'),
    ('Boinaire (Sinte Eustatius i Saba)'),
    ('Bosnia i Hercegovina'),
    ('Botswana'),
    ('Brasil'),
    ('Brunei'),
    ('Bulgaria'),
    ('Burkina Faso'),
    ('Burundi'),
    ('Cambodja'),
    ('Camerun'),
    ('Canada'),
    ('Cap Verd'),
    ('Comores'),
    ('Confederacio Suissa'),
    ('Congo'),
    ('Corea del Nord'),
    ('Corea del Sud'),
    ('Costa d''Ivori'),
    ('Costa Rica'),
    ('Croacia'),
    ('Cuba'),
    ('Curacao'),
    ('Dinamarca'),
    ('Djibouti'),
    ('Egipte'),
    ('Emirats Arabs Units'),
    ('Eritrea'),
    ('Eslovaquia'),
    ('Eslovenia'),
    ('Estonia'),
    ('Eswatini'),
    ('Fiji'),
    ('Filipines'),
    ('Finlandia'),
    ('França'),
    ('Gabon'),
    ('Gambia'),
    ('Georgia'),
    ('Ghana'),
    ('Gibraltar'),
    ('Grecia'),
    ('Grenada'),
    ('Groenlandia'),
    ('Guadalupe'),
    ('Guaiana Francesa'),
    ('Guam'),
    ('Guatemala'),
    ('Guernsey'),
    ('Guinea'),
    ('Guinea Bissau'),
    ('Guinea Equatorial'),
    ('Guyana'),
    ('Haiti'),
    ('Hong Kong'),
    ('Hongria');
INSERT INTO Pais (Nom_pais)
VALUES ('Iemen'),
    ('Illa Bouvet'),
    ('Illa Christmas'),
    ('Illa de la Reunio'),
    ('Illa de Man'),
    ('Illa Norfolk'),
    ('Illes Aland'),
    ('Illes Caiman'),
    ('Illes Cocos (Keeling)'),
    ('Illes Cook'),
    ('Illes Falkland (Malvines)'),
    ('Illes Feroe'),
    ('Illes Georgia del Sud i Sandwich del Sud'),
    ('Illes Heard i McDonald'),
    ('Illes Mariannes Septentrionals'),
    ('Illes Marshall'),
    ('Illes Menors Allunyades dels Estats Units'),
    ('Illes Salomo'),
    ('Illes Turks i Caicos'),
    ('Illes Verges Britaniques'),
    ('India'),
    ('Indonesia'),
    ('Iran'),
    ('Iraq'),
    ('Irlanda'),
    ('Islandia'),
    ('Israel'),
    ('Italia'),
    ('Jamaica'),
    ('Japo'),
    ('Jersey'),
    ('Jordania'),
    ('Kazakhstan'),
    ('Kenya'),
    ('Kirguizstan'),
    ('Kiribati'),
    ('Kuwait'),
    ('Lao'),
    ('Lesotho'),
    ('Letonia'),
    ('Liban'),
    ('Liechtenstein'),
    ('Lituania'),
    ('Luxemburg'),
    ('Macau'),
    ('Macedonia del Nord'),
    ('Madagascar'),
    ('Malaisia'),
    ('Malawi'),
    ('Maldives'),
    ('Malta'),
    ('Martinica'),
    ('Maurici'),
    ('Mauritania'),
    ('Mayotte'),
    ('Mexic'),
    ('Micronesia (Estats Federats de)'),
    ('Moçambic'),
    ('Moldavia'),
    ('Monaco'),
    ('Mongolia'),
    ('Montenegro'),
    ('Montserrat'),
    ('Myanmar'),
    ('Namibia'),
    ('Nauru'),
    ('Nepal'),
    ('Nicaragua'),
    ('Niger'),
    ('Nigeria'),
    ('Niue'),
    ('Noruega'),
    ('Nova Caledonia'),
    ('Nova Zelanda'),
    ('Oman');
INSERT INTO Pais (Nom_pais)
VALUES ('Paisos Baixos'),
    ('Palau'),
    ('Palestina'),
    ('Panama'),
    ('Papua Nova Guinea'),
    ('Pitcairn'),
    ('Polinesia Francesa'),
    ('Polonia'),
    ('Portugal'),
    ('Puerto Rico'),
    ('Qatar'),
    ('Regne Unit'),
    ('Romania'),
    ('Ruanda'),
    ('Russia'),
    ('Sahara Occidental'),
    ('Saint Helena (Ascension i Tristan da Cunha)'),
    ('Saint Kitts i Nevis'),
    ('Saint Lucia'),
    ('Saint Vincent i les Grenadines'),
    ('Saint Barthelemy'),
    ('Saint Martin (Part Francesa)'),
    ('Saint Pierre et Miquelon'),
    ('Samoa'),
    ('Samoa Americana'),
    ('San Marino'),
    ('Santa Seu (Estat del Vatica)'),
    ('Sao Tome i Principe'),
    ('Servia'),
    ('Seychelles'),
    ('Sierra Leone'),
    ('Singapur'),
    ('Sin Marteen (Part Neerlandesa)'),
    ('Siria'),
    ('Somalia'),
    ('Sri Lanka'),
    ('Sud Africa'),
    ('Sudan'),
    ('Sudan del Sud'),
    ('Suecia'),
    ('Suissa'),
    ('Surinam'),
    ('Svalbard i Jan Mayen'),
    ('Tadjikistan'),
    ('Tailandia'),
    ('Taiwan'),
    ('Tanzania'),
    ('Timor Leste'),
    ('Togo'),
    ('Tokelau'),
    ('Tonga'),
    ('Trinitat i Tobago'),
    ('Tunisia'),
    ('Turkmenistan'),
    ('Turquia'),
    ('Tuvalu'),
    ('Txad'),
    ('Txequia'),
    ('Ucraina'),
    ('Uganda'),
    ('Unio de les Comores'),
    ('Uruguai'),
    ('Uzbekistan'),
    ('Vanuatu'),
    ('Vietnam'),
    ('Wallis i Futuna'),
    ('Xile'),
    ('Xipre'),
    ('Zambia'),
    ('Zimbabue');
INSERT INTO Situacio_economica (Nom)
VALUES ('Jubilat/ada'),
    ('En situació de dependència'),
    ('Sense permís de treball'),
    ('Economia submergida'),
    ('Treballs reproductius (cures)');
INSERT INTO Rol (Nom_rol)
VALUES ('Mare'),
    ('Pare'),
    ('Fill/a'),
    ('Avi/a'),
    ('Tiet/a'),
    ('Tutor/a legal');
INSERT INTO Sebas (Nom)
VALUES ('SEBAS 1'),
    ('SEBAS 2.1'),
    ('SEBAS 2.2'),
    ('SEBAS 3'),
    ('SEBAS 4.1'),
    ('SEBAS 4.2'),
    ('SEBAS 5.1 i 5.2'),
    ('SEBAS 6.1 i 6.3'),
    ('SEBAS 6.2'),
    ('SEBAS 7'),
    ('Model SIS');
INSERT INTO Necessitats_especials (Nom_necessitat)
VALUES ('Amb diagnòstic'),
    ('En procés de diagnòstic'),
    ('No NESE'),
    ('Sospita');
INSERT INTO Curs_actual (Nom)
VALUES ('I3'),
    ('I4'),
    ('I5'),
    ('1r primaria'),
    ('2n primaria'),
    ('3r primaria'),
    ('4t primaria'),
    ('5e primaria'),
    ('6e primaria'),
    ('1r ESO'),
    ('2n ESO'),
    ('3r ESO'),
    ('4t ESO'),
    ('1r Batx'),
    ('2n Batx'),
    ('1r CFGM'),
    ('2n CFGM'),
    ('1r CFGS'),
    ('2n CFGS'),
    ('1r Grau'),
    ('2n Grau'),
    ('3r Grau'),
    ('4t Grau'),
    ('PFI'),
    ('Altres');
INSERT INTO Tipus_domicili (Nom_domicili)
VALUES ('Lloguer'),
    ('Hipoteca'),
    ('Ocupacio'),
    ('Compartit'),
    ('Habitatge d''emergència'),
    ('Recurs residencial'),
    ('Altres');
INSERT INTO Genere (Nom_genere)
VALUES ('Masculí'),
    ('Femení'),
    ('Non binari');
INSERT INTO `Estructura_familiar` (`Nom_est_fam`)
VALUES ('biparental'),
    ('monoparental (pare)'),
    ('monoparental (mare)'),
    ('tutor legal (extrafamiliar)'),
    ('tutor legal (intrafamiliar)'),
    ('divorci amb custòdia compartida');